D_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('', include('news.urls')),
    path('users/', include('user.urls')),
    path('', include('verifications.urls')),
    path('doc', include('doc.urls')),
    path('course', include('course.urls')),
    path('admin/', include('admin.urls')),

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/admin/urls.py
# -*- coding:utf-8 -*-

from django.urls import path
from admin import views


app_name = 'admin'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('tags/', views.TagManageView.as_view(), name='tags'),
    path('tags/<tag_id>/', views.TagEditView.as_view(), name='tag_edit'),

    path('hotnews/', views.HotNewsManage.as_view(), name='hotnews'),
    path('hotnews/<int:hotnews_id>/', views.HotNewsEdit.as_view(), name='hotnews_ID'),
    path('hotnews/add/', views.HotNewsAdd.as_view(), name='hotnews_add'),
    path('tags/<int:tag_id>/news/', views.NewsByTagID.as_view(), name='news_by_tagid'),

    path('news/',views.NewsManage.as_view(),name='news_manage'),
    path('news/<int:news_id>/',views.NewsEditView.as_view(),name='news_edit'),
    path('news/pub/',views.NewsPubView.as_view(),name='news_pub'),

    path('news/images/',views.NewsUploadImage.as_view(),name='upload_image'),
    path('token/',views.UploadToken.as_view(),name='upload_token'),
    path('markdown/images/',views.MarkDownUploadImage.as_view(),name='markdown_image_upload'),

    path('docs/', views.DocsManageView.as_view(), name='docs_manage'),
    path('docs/<int:doc_id>/', views.DocEditView.as_view(), name='docs_edit'),
    path('docs/files/', views.DocUploadFile.as_view(), name='upload_file'),
    path('docs/pub/', views.DocsPubView.as_view(), name='doc_pub'),

    path('courses/', views.CoursesManageView.as_view(), name='courses_manage'),
    path('courses/<int:course_id>/', views.CourseEditView.as_view(), name='courses_edit'),
    path('courses/pub/', views.CoursePubView.as_view(), name='courses_pub'),

    path('banners/', views.BannerManageView.as_view(), name='banners_manage'),
    path('banners/<int:banner_id>/', views.BannerEditView.as_view(), name='banners_edit'),
    path('banners/add/', views.BannerAddView.as_view(), name='banners_add'),

    path('groups/',views.GroupManageView.as_view(), name='group_manage'),
    path('groups/<int:group_id>/', views.GroupEditView.as_view(), name='group_edit'),
    path('groups/add/', views.GroupAddView.as_view(), name='group_add'),

    path('users/', views.UsersManageView.as_view(), name='users_manage'),
    path('users/<int:user_id>/', views.UsersEditView.as_view(), name='users_edit'),

]

apps/doc/urls.py
# -*- coding:utf-8 -*
from django.urls import path
from doc import views


app_name = 'doc'

urlpatterns = [
    path('', views.doc_index, name='index'),
    path('<int:doc_id>/', views.DocDownload.as_view(), name='download'),
]

apps/news/urls.py
# -*- coding:utf-8 -*-
from django.urls import path
from news import views


app_name = 'news'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('news/', views.NewsListView.as_view(), name='news_list'),
    path('news/banners/', views.NewsBannerView.as_view(), name='news_banner'),
    path('news/<int:news_id>/', views.NewDetailView.as_view(), name='news_detail'),
    path('news/<int:news_id>/comments/', views.NewsCommentView.as_view(), name='news_comment'),
    path('search/', views.SearchView(), name='search'),

]

apps/user/urls.py
# -*- coding:utf-8 -*-
from django.urls import path,include
from user import views


app_name = 'user'

urlpatterns = [
    path('register/',views.RegisterView.as_view(),name='register'),
    path('login/',views.LoginView.as_view(),name='login'),
    path('logout/',views.LogoutView.as_view(),name='logout'),
]

templates/base/news_index_base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>
    {% block title %}

    {% endblock%}
  </title>
  <link rel="shortcut icon" type="image/png" href="../../static/images/favicon.ico">
  <link rel="stylesheet" href="../../static/css/base/reset.css">
  <link rel="stylesheet" href="../../static/css/base/common.css">
  <link rel="stylesheet" href="http://at.alicdn.com/t/font_684044_un7umbuwwfp.css">
    {% block link%}

    {% endblock %}

</head>
<body>
<!-- header start -->
<header id="header">
  <div class="mw1200 header-contain clearfix">
    <!-- logo start -->
    <h1 class="logo">
      <a href="javascript:void(0);" class="logo-title">Python</a>
    </h1>
    <!-- logo end -->
    <!-- nav start -->
    <nav class="nav">
      <ul class="menu">
        <li><a href="{% url 'news:index' %}">首页</a></li>
        <li><a href="{% url 'course:index' %}">在线课堂</a></li>
        <li><a href="{% url 'doc:index' %}">下载文档</a></li>
        <li><a href="{% url 'news:search' %}">搜索</a></li>
      </ul>
    </nav>
    <!-- nav end -->
    <!-- login start -->
      <div class="login-box">
          {% if user.is_authenticated %}        {#判断user表能否获取到#}
              <div class="author">
                  <i class="PyWhich py-user"></i>
                  <span>{{ user.username }}</span>
                  <ul class="author-menu">
                      {% if user.is_staff %}     {# 判断用户是否有is_staff权限 #}
                      <li><a href="{% url 'admin:index' %}">后台管理</a></li>
                      {% endif %}
                      <li><a href="{% url 'user:logout' %}">退出登录</a></li>
                  </ul>
              </div>
          {% else %}
          <div>
              <i class="PyWhich py-user"></i>
              <span>
                  <a href="{% url 'user:login' %}" class="login">登录</a> /
                  <a href="{% url 'user:register'%}" class="reg">注册</a>
              </span>
          </div>
          {% endif %}
      </div>
    <!-- login end -->
  </div>
</header>
<!-- header end -->

<!-- main start -->
{% block main_start %}
<main id="main">
<div class="w1200 clearfix">
<!-- main-contain start  -->
  {% block main-contain%}

  {% endblock%}
<!-- main-contain  end -->

<!-- side start -->
  {% block side%}
      <aside class="side">
      <div class="side-activities">
          <h3 class="activities-title">在线课堂<a href="javascript:void(0)">更多</a></h3>
          <div class="activities-img">
              <a href="javascript:void(0);" target="_blank">
                  <img src="../../static/images/english.jpg" alt="title">
              </a>
              <p class="activities-tips">对话国外小姐姐</p>
          </div>
          <ul class="activities-list">
              <li>
                  <a href="javascript:void(0);" target="_blank">
                      <span class="active-status active-start">报名中</span>
                      <span class="active-title"><a
                              href="https://www.shiguangkey.com/course/2432"> Django 项目班</a></span>
                  </a>
              </li>
              <li>
                  <a href="javascript:void(0);" target="_blank">
                      <span class="active-status active-end">已结束</span>
                      <span class="active-title"><a
                              href="https://www.shiguangkey.com/course/2321">Python入门基础班</a></span>
                  </a>
              </li>
          </ul>
      </div>
      <div class="side-attention clearfix">
          <h3 class="attention-title">关注我</h3>
          <ul class="side-attention-address">
              <li>
                  <a href="javascript:void(0);" target="_blank"><i class="PyWhich py-GitHub"></i>Taka</a>
              </li>
              <li>
                  <a href="javascript:void(0);" target="_blank"><i class="PyWhich py-zhihu"
                                                                   style="color:rgb(0, 108, 226);"></i>Taka</a>
              </li>
              <li>
                  <a href="javascript:void(0);" target="_blank"><i class="PyWhich py-weibo"
                                                                   style="color:rgb(245,92,110);"></i>Taka</a>
              </li>
          </ul>
          <div class="side-attention-qr">
              <p>扫码关注</p>
          </div>
      </div>

      <div class="side-hot-recommend">
          <h3 class="hot-recommend">热门推荐</h3>
          <ul class="hot-news-list">

              <li>
                  <a href="javascript:void(0)" class="hot-news-contain clearfix">
                      <div class="hot-news-thumbnail">
                          <img src="../../static/images/python_web.jpg"
                               alt="">
                      </div>
                      <div class="hot-news-content">
                          <p class="hot-news-title">Django调试工具django-debug-toolbar安装使用教程</p>
                          <div class="hot-news-other clearfix">
                              <span class="news-type">python框架</span>
                              <!-- 自带的 -->
                              <time class="news-pub-time">11月11日</time>
                              <span class="news-author">python</span>
                          </div>
                      </div>
                  </a>
              </li>

          </ul>
      </div>


  </aside>
  {% endblock%}

<!-- side end -->
</div>
</main>
{% endblock%}
<!-- main end -->

<!-- footer start -->
<footer id="footer">
    <div class="footer-box">
        <div class="footer-content">
            <p class="top-content">
					<span class="link">
						<a href="javascript:void(0)">关于Python</a> |
						<a href="javascript:void(0)">我就是我</a> |
						<a href="javascript:void(0)">人生苦短</a> |
						<a href="javascript:void(0)">我用Python</a>
					</span>
                <span class="about-me">关于我: <i class="PyWhich py-wechat"></i>moke</span>
            </p>
            <p class="bottom-content">
                <span>地址： xxxx</span>
                <span>联系方式: <a href="tel:400-1567-315">400-1567-315</a> (24小时在线)</span>
            </p>
        </div>
        <p class="copyright-desc">
            Copyright &copy; 2008 - 2019 xxx有限公司. All Rights Reserved
        </p>
    </div>
</footer>
<!-- footer end -->
<script src="../../static/js/jquery.js"></script>
<script src="../../static/js/commons.js"></script>
<script src="../../static/js/admin/base/message.js"></script>

{% block script %}

{% endblock %}

</body>
</html>