D_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('', include('news.urls')),
    path('users/', include('user.urls')),
    path('', include('verifications.urls')),
    path('doc', include('doc.urls')),
    path('course', include('course.urls')),
    path('admin/', include('admin.urls')),

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/news/urls.py
# -*- coding:utf-8 -*-
from django.urls import path
from news import views


app_name = 'news'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('news/', views.NewsListView.as_view(), name='news_list'),
    path('news/banners/', views.NewsBannerView.as_view(), name='news_banner'),
    path('news/<int:news_id>/', views.NewDetailView.as_view(), name='news_detail'),
    path('news/<int:news_id>/comments/', views.NewsCommentView.as_view(), name='news_comment'),
    path('search/', views.SearchView(), name='search'),

]

apps/news/models.py
from django.db import models
from utils.models import ModelBase  # 用来继承的三个字段
from django.core.validators import MinLengthValidator

# 文章分类表
class Tag(ModelBase):
    """
    name：标签名称
    """
    name = models.CharField(max_length=64, verbose_name="标签名", help_text="标签名")

    class Meta:
        ordering = ['-update_time','-id']        # 排序：按照更新时间，id从大到小排序
        db_table = "tb_tag"                 # 数据库中创建的表名
        verbose_name = "新闻标签"            # 在admin站点中显示的名称
        verbose_name_plural = verbose_name  # 显示的复数名称

    def __str__(self):
        return self.name                    # 访问Tag实例，返回标签名称给我们


# 文章表
class News(ModelBase):
    """
     title  digest(摘要)  content clicks(访问量)   image_url
     author(作者，关联用户表一对多(一个人写多文章))
     tag(外键关联一对多(一个分类多篇文章))
    """
    # models.CharField中没有提供min_length参数，需要使用校验器才能设置最小长度
    title = models.CharField(max_length=150, validators=[MinLengthValidator(1)],verbose_name="标题", help_text="标题")
    digest = models.CharField(max_length=200, validators=[MinLengthValidator(1)],verbose_name="摘要", help_text="摘要")
    content = models.TextField(verbose_name="内容", help_text="内容")
    clicks = models.IntegerField(default=0, verbose_name="点击量", help_text="点击量")
    image_url = models.URLField(default="", verbose_name="图片url", help_text="图片url")

    # on_delete:当Tag中删除了某分类，则New中文章类别为None
    tag = models.ForeignKey('Tag', on_delete=models.SET_NULL, null=True)
    # on_delete:当作者不存在，则New中文章作者为None
    author = models.ForeignKey('user.Users', on_delete=models.SET_NULL, null=True)

    class Meta:
        ordering = ['-update_time', '-id']      # 排序
        db_table = "tb_news"                    # 指明数据库表名
        verbose_name = "新闻"                   # 在admin站点中显示的名称
        verbose_name_plural = verbose_name      # 显示的复数名称

    def __str__(self):
        return self.title          # 访问News实例，返回新闻标题称给我们


# 评论表
class Comments(ModelBase):
    """
     content(评论内容)
     author(评论人，关联用户表一对多(一个用户写多条评论))
     news(哪篇文章，关联文章表一对多(一篇文章有多条评论))
    """
    content = models.TextField(verbose_name="内容", help_text="内容")
    author = models.ForeignKey('user.Users', on_delete=models.SET_NULL, null=True)
    # 级联删除，也就是当删除主表的数据时候从表中的数据也随着一起删除
    news = models.ForeignKey('News', on_delete=models.CASCADE)
    parent = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True)

    # 生成序列化输出的字典
    def to_dict_data(self):
        comment_dict = {
            'news_id': self.news_id,
            'comment_id': self.id,
            'content': self.content,
            'author': self.author.username,
            'update_time': self.update_time.strftime('%Y年%m月%d日 %H:%M'),
            'parent': self.parent.to_dict_data() if self.parent else None
        }
        return comment_dict


    class Meta:
        ordering = ['-update_time', '-id']        # 排序
        db_table = "tb_comments"                  # 指明数据库表名
        verbose_name = "评论"                     # 在admin站点中显示的名称
        verbose_name_plural = verbose_name        # 显示的复数名称

    def __str__(self):
        return '<评论{}>'.format(self.id)


# 热门文章表
class HotNews(ModelBase):
    """
    news(关联文章一对一)
    priority(优先级)
    """
    PTL_CHOICES = [
        (1, '第一级'),
        (2, '第二级'),
        (3, '第三级'),
    ]
    # models.CASCADE：级联删除
    news = models.OneToOneField('News', on_delete=models.CASCADE)
    # choices限制优先级范围
    priority = models.IntegerField(choices=PTL_CHOICES, default=3, verbose_name="优先级", help_text="优先级")

    class Meta:
        ordering = ['-update_time', '-id']          # 排序
        db_table = "tb_hotnews"                     # 指明数据库表名
        verbose_name = "热门新闻"                    # 在admin站点中显示的名称
        verbose_name_plural = verbose_name          # 显示的复数名称

    def __str__(self):
        return '<热门新闻{}>'.format(self.id)


# 轮播图表
class Banner(ModelBase):
    """
    image_url   priority(优先级)   news(关联文章一对一)
    """
    PTL_CHOICES = [
        (1, '第一级'),
        (2, '第二级'),
        (3, '第三级'),
        (4, '第四级'),
        (5, '第五级'),
        (6, '第六级'),
    ]
    image_url = models.URLField(verbose_name="轮播图url", help_text="轮播图url")
    # choices限制优先级范围
    priority = models.IntegerField(choices=PTL_CHOICES, default=6, verbose_name="优先级", help_text="优先级")
    # models.CASCADE：级联删除
    news = models.OneToOneField('News', on_delete=models.CASCADE)

    class Meta:
        ordering = ['priority', '-update_time', '-id']  # 排序
        db_table = "tb_banner"                          # 指明数据库表名
        verbose_name = "轮播图"                          # 在admin站点中显示的名称
        verbose_name_plural = verbose_name              # 显示的复数名称

    def __str__(self):
        return '<轮播图{}>'.format(self.id)

apps/news/views.py
import json
import logging
from django.shortcuts import render
from django.views import View
from django.http import Http404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger  # django中的分页方法
from haystack.views import SearchView as _SearchView        # 搜索页

from D_project import settings
from news import models
from news import  constants
from utils.json_fun import to_json_data
from utils.user_reg_code import Code,error_map

# 日志器
logger = logging.getLogger('django')


# 首页
class IndexView(View):
    """使用context渲染"""
    def get(self, request):
        # 文章标签导航实现
        tags = models.Tag.objects.only('id', 'name').filter(is_delete=False)
        # 热门新闻功能实现
        hot_news = models.HotNews.objects.select_related('news').\
            only('news__title','news__image_url','news_id').filter(is_delete=False).\
            order_by('priority','-news__clicks')[0:constants.SHOW_HOTNEWS_COUNT]
            # order_by:从优先级或者点击量(从大到小)进行排序,[]:切片方法显示1-3条
        # context = {
        #     'tags': tags
        # }
        # return render(request, 'news/index.html',context=context)
        return render(request, 'news/index.html', locals())     # locals()方法代替context{}方法


# 新闻列表页
class NewsListView(View):
    """
     前端发送：ajax请求
     传参：tag_id(标签分类id)   page(标签下对应文章页数)
     后台返回：7个字段
     请求方式：GET（只是查询，不涉及其他）
     url定义：/news/?tag_id=1&page=2
    """
    def get(self, request):
        # 1.获取前端参数
        # 2.校验参数:正常传参(传数字)，异常传参(爬虫程序传来字母)
        try:
            tag_id = int(request.GET.get('tag_id', 0))   # 拿到的是字符串类型，需要转换;没有传参就为0
        except Exception as e:
            logger.error("传入标签错误:\n{}".format(e))   # 写入日志器
            tag_id = 0
        try:
            page = int(request.GET.get('page', 1))
        except Exception as e:
            logger.error("页码错误:\n{}".format(e))
            page = 1

        # 3.从数据库拿数据
        # select_related:优化查询,当执行它的查询时它沿着外键关系查询关联的对象数据
        news_queryset = models.News.objects.select_related('tag','author').only('title','image_url'
                        ,'digest','update_time','tag__name','author__username').filter()
        # 传了tag_id按标签查，没传就查询数据库所有的
        news= news_queryset.filter(is_delete=False, tag_id=tag_id) or news_queryset.filter(is_delete=False)

        # 4.分页
        paginator = Paginator(news, constants.PER_PAGE_NEWS_COUNT)   # 对news进行分页，每页xx条
        try:
            news_info = paginator.page(page)     # 拿到具体某一页的信息,是quertset类型
        except EmptyPage:                        # 例如：最多5页，传的page>5
            logger.error("访问页数不存在！")
            news_info = paginator.page(paginator.num_pages)     # 返回最后一页(num_pages代表总页数)

        # 5.序列化输出
        news_info_list = []
        for n in news_info:
            news_info_list.append({
                'id': n.id,
                'title': n.title,
                'digest': n.digest,
                'image_url': n.image_url,
                'update_time': n.update_time.strftime('%Y年%m月%d日 %H:%M'),    # 格式化时间
                'tag_name': n.tag.name,
                'author': n.author.username,
            })
        data = {
            'news': news_info_list,
            'total_pages': paginator.num_pages
        }
        # 6.返回数据给前端
        return to_json_data(data=data)


# 轮播图
class NewsBannerView(View):
    """
    请求方法：GET
    url定义：/news/banners/
    请求参数：前端无需传入参数
    ajax渲染，后端返回json格式数据
    """
    def get(self,request):
        # 1.数据库中查询返回字段
        banners = models.Banner.objects.select_related('news').only('image_url','news_id','news__title').\
            filter(is_delete=False).order_by('priority')[0:constants.SHOW_BANNER_COUNT]
        # 2.序列化输出
        banners_info_list = []
        for b in banners:
            banners_info_list.append(
                {
                    'image_url': b.image_url,
                    'news_id': b.news_id,
                    'new_title': b.news.title,
                }
            )
        data = {
            'banners': banners_info_list
        }
        return to_json_data(data=data)


# 文章详情页
class NewDetailView(View):
    """
    前端传参：news_id
    后台返回：title,author,update_time,tag_name, content
    url定义:'/news/<int:news_id>'
    """
    def get(self,request,news_id):
        # 文章详情
        news = models.News.objects.select_related('tag', 'author').\
            only('title','author', 'update_time','tag__name','content').\
            filter(is_delete=False, id=news_id).first()
        if news:
            # 评论部分字段：author,content,update_time, parent.username, parent.content, parent.update_time
            comments = models.Comments.objects.select_related('author', 'parent').\
                only('content', 'update_time', 'author__username', 'parent__content',
                     'parent__author__username', 'parent__update_time').\
                filter(is_delete=False,news_id=news_id)
            # 序列化输出(字典在模型中生成)
            comments_list = []
            for c in comments:
                comments_list.append(c.to_dict_data())   # c.to_dict_data()调用模型类的方法
            return render(request,'news/news_detail.html',locals())
        else:
            raise Http404('文章{}不存在'.format(news_id))


# 文章评论
class NewsCommentView(View):
    """
    前端传参：news_id(通过url传递),content,parent_id(也可以没有)，当前用户：request.user
    URL:/news/<int:news_id>/comments/
    """
    def post(self,request,news_id):
        # 1.获取参数
        if not request.user.is_authenticated:         # 判断是否登录
            return to_json_data(errno=Code.SESSIONERR,errmsg=error_map[Code.SESSIONERR])

        if not models.News.objects.only('id').filter(is_delete=False,id=news_id):
            return to_json_data(errno=Code.PARAMERR,errmsg='新闻不存在')

        json_data = request.body       # 从body中获取
        if not json_data:
            return to_json_data(errno=Code.PARAMERR, errmsg=error_map[Code.PARAMERR])
        dict_data = json.loads(json_data.decode('utf8'))

        # 2.校验参数
        content = dict_data.get('content')
        if not content:
            return to_json_data(errno=Code.PARAMERR, errmsg='评论内容不能为空')

        # 父评论验证：是否存在，parent_id必须为数字，数据库是否存在, 父评论新闻id是否等于news_id
        parent_id = dict_data.get('parent_id')
        try:
            if parent_id:
                parent_id = int(parent_id)
                if not models.Comments.objects.only('id').filter(is_delete=False,id=parent_id,
                                                                news_id=news_id).exists():
                    return to_json_data(errno=Code.PARAMERR, errmsg=error_map[Code.PARAMERR])
        except Exception as e:
            logger.info('前端传的parent_id有误{}'.format(e))
            return to_json_data(errno=Code.PARAMERR, errmsg='未知错误')

        # 3.存入数据库
        new_comment = models.Comments()
        new_comment.content = content
        new_comment.news_id = news_id
        new_comment.author = request.user
        new_comment.parent_id = parent_id if parent_id else None
        new_comment.save()

        # 4.返回给前端
        return to_json_data(data=new_comment.to_dict_data())   # 调用模型中的序列化输出


# 搜索页
class SearchView(_SearchView):             # 使用haystack一个查询的类
    # 模版文件
    template = 'news/search.html'
    # 重写响应方式，如果请求参数q为空，返回模型News的热门新闻数据，否则根据参数q搜索相关数据
    def create_response(self):
        kw = self.request.GET.get('q', '')
        if not kw:
            show_all = True     # 显示所有数据
            hot_news = models.HotNews.objects.select_related('news'). \
                only('news__title', 'news__image_url', 'news__id'). \
                filter(is_delete=False).order_by('priority', '-news__clicks')
            # 对搜索结果进行分页
            paginator = Paginator(hot_news, settings.HAYSTACK_SEARCH_RESULTS_PER_PAGE)
            try:
                # 拿到page具体参数，没有就默认获取第1页
                page = paginator.page(int(self.request.GET.get('page', 1)))
            except PageNotAnInteger:
                # 如果参数page的数据类型不是整型，则返回第一页数据
                page = paginator.page(1)
            except EmptyPage:
                # 用户访问的页数大于实际页数，则返回最后一页的数据
                page = paginator.page(paginator.num_pages)
            return render(self.request, self.template, locals())
        else:
            show_all = False
            qs = super(SearchView, self).create_response()
            return qs

templates/news/index.html
{% extends 'base/news_index_base.html' %}


{% block title %}
    首页
{% endblock %}


{% block link %}
    <link rel="stylesheet" href="../../static/css/news/index.css">
    <link rel="stylesheet" href="../../static/css/base/side.css">
{% endblock %}


{% block main-contain %}
     <div class="main-contain">
      <!-- banner start -->
        <div class="banner">
            <ul class="pic">
                <!--淡入淡出banner-->


            </ul>
            <a href="javascript:void(0);" class="btn prev">
                <i class="PyWhich py-arrow-left"></i></a>
            <a href="javascript:void(0);" class="btn next">
                <i class="PyWhich py-arrow-right"></i></a>
            <ul class="tab">
                <!-- 按钮数量必须和图片一致 -->


            </ul>
        </div>
      <!-- banner end -->

      <!-- content start -->
      <div class="content">
        <!-- recommend-news start -->
          <ul class="recommend-news">
               {% for n in hot_news %}
                    <li>
                        <a href="{% url 'news:news_detail' n.news.id %}" target="_blank">
                            <div class="recommend-thumbnail">
                                <img src="{{ n.news.image_url }}" alt="title">
                            </div>
                            <p class="info">{{ n.news.title }}</p>
                        </a>
                    </li>
                {% endfor %}

          </ul>
        <!-- recommend-news end -->

        <!--  news-nav start-->
          <nav class="news-nav">
              <ul class="clearfix">
                  <li class="active"><a href="javascript:void(0)">最新资讯</a></li>
                  {% for tag in tags %}
                      <li><a href="javascript:void(0)" data-id="{{ tag.id}}">{{ tag.name }}</a></li>
                  {% endfor %}

              </ul>
          </nav>
        <!--  news-nav end -->

        <!-- news-contain start -->
          <div class="news-contain">
              <ul class="news-list">

              </ul>
          </div>
        <!-- news-contain end -->

        <!-- btn-more start -->
{#        <a href="javascript:void(0);" class="btn-more">加载更多</a>#}
        <!-- btn-more end -->
      </div>
      <!-- content end -->
    </div>
{% endblock %}


{% block script %}
    <script src="../../static/js/news/index.js"></script>
{% endblock %}

templates/news/news_detail.html
{% extends 'base/news_index_base.html' %}

{% block title %}
    文章详情
{% endblock %}

{% block link %}
    <link rel="stylesheet" href="../../static/css/news/news-detail.css">
    <link rel="stylesheet" href="../../static/css/base/side.css">
{% endblock %}

{% block main-contain%}
        <div class="news-contain">
      <h1 class="news-title">{{ news.title }}</h1>
      <div class="news-info">
        <div class="news-info-left">
          <span class="news-author">{{ news.author.username }}</span>
          <span class="news-pub-time">{{ news.update_time }}</span>
          <span class="news-type">{{ news.tag.name }}</span>
        </div>
      </div>
      <article class="news-content">
        {{ news.content|safe }}
      </article>
    <div class="comment-contain">
      <div class="comment-pub clearfix">
        <div class="new-comment">
          文章评论(<span class="comment-count">0</span>)
        </div>

        {% if user.is_authenticated %}
          <div class="comment-control logged-comment" news-id="{{ news.id }}">
            <input type="text" placeholder="请填写评论">
            <button class="comment-btn">发表评论</button>
          </div>
        {% else %}
          <div class="comment-control please-login-comment" news-id="{{ news.id }}">
            <input type="text" placeholder="请登录后参加评论" readonly>
            <button class="comment-btn">发表评论</button>
          </div>
        {% endif %}

      </div>

      <ul class="comment-list">
        {% for one_comment in comments_list %}
          <li class="comment-item">
            <div class="comment-info clearfix">
              <img src="{% static 'images/avatar.jpeg' %}" alt="avatar" class="comment-avatar">
              <span class="comment-user">{{ one_comment.author }}</span>
            </div>
            <div class="comment-content">{{ one_comment.content }}</div>

            {% if one_comment.parent %}
              <div class="parent_comment_text">
                <div class="parent_username">{{ one_comment.parent.author }}</div>
                <br/>
                <div class="parent_content_text">
                  {{ one_comment.parent.content }}
                </div>
              </div>
            {% endif %}

            <div class="comment_time left_float">{{ one_comment.update_time }}</div>
            <a href="javascript:;" class="reply_a_tag right_float">回复</a>
            <form class="reply_form left_float" comment-id="{{ one_comment.comment_id }}"
                  news-id="{{ one_comment.news_id }}">
              <textarea class="reply_input"></textarea>
              <input type="button" value="回复" class="reply_btn right_float">
              <input type="reset" name="" value="取消" class="reply_cancel right_float">
            </form>

          </li>
        {% endfor %}

      </ul>
    </div>
    </div>

{% endblock%}

{% block script %}
    <script src="../../static/js/news/news_detail.js"> </script>
{% endblock %}

templates/news/search.html
{% extends 'base/news_index_base.html' %}


{% block title %}
    搜索
{% endblock %}


{% block link %}
    <link rel="stylesheet" href="../../static/css/news/search.css">
    <link rel="stylesheet" href="../../static/css/base/side.css">
{% endblock %}


{% block main-contain %}
    <div class="main-contain ">
        <!-- search-box start -->
        <div class="search-box">
            <form action="" style="display: inline-flex;">

                <input type="search" placeholder="请输入要搜索的内容" name="q" class="search-control">


                <input type="submit" value="搜索" class="search-btn">
            </form>
            <!-- 可以用浮动 垂直对齐 以及 flex  -->
        </div>
        <!-- search-box end -->
        <!-- content start -->
        <div class="content">
            <!-- search-list start -->
            {% if not show_all %}
                <div class="search-result-list">
                    <h2 class="search-result-title">
                        搜索结果: <span style="font-weight: 700;color: #ff6620;">{{ paginator.num_pages }}</span>页
                    </h2>
                    <ul class="news-list">
                        {# 导入自带高亮功能 #}
                        {% load highlight %}
                        {% for one_news in page.object_list %}
                            <li class="news-item clearfix">
                                <a href="{% url 'news:news_detail' one_news.id %}" class="news-thumbnail"
                                   target="_blank">
                                    <img src="{{ one_news.object.image_url }}">
                                </a>
                                <div class="news-content">
                                    <h4 class="news-title">
                                        <a href="{% url 'news:news_detail' one_news.id %}">
                                            {% highlight one_news.title with query %}
                                        </a>
                                    </h4>
                                    <p class="news-details">{% highlight one_news.digest with query %}</p>
                                    <div class="news-other">
                                        <span class="news-type">{{ one_news.object.tag.name }}</span>
                                        <span class="news-time">{{ one_news.object.update_time }}</span>
                                        <span class="news-author">{% highlight one_news.object.author.username with query %}
                                      </span>
                                    </div>
                                </div>
                            </li>
                        {% endfor %}


                    </ul>
                </div>

            {% else %}

                <div class="news-contain">
                    <div class="hot-recommend-list">
                        <h2 class="hot-recommend-title">热门推荐</h2>
                        <ul class="news-list">

                            {% for one_hotnews in page.object_list %}

                                <li class="news-item clearfix">
                                    <a href="#" class="news-thumbnail">
                                        <img src="{{ one_hotnews.news.image_url }}">
                                    </a>
                                    <div class="news-content">
                                        <h4 class="news-title">
                                            <a href="{% url 'news:news_detail' one_hotnews.news.id %}">{{ one_hotnews.news.title }}</a>
                                        </h4>
                                        <p class="news-details">{{ one_hotnews.news.digest }}</p>
                                        <div class="news-other">
                                            <span class="news-type">{{ one_hotnews.news.tag.name }}</span>
                                            <span class="news-time">{{ one_hotnews.update_time }}</span>
                                            <span class="news-author">{{ one_hotnews.news.author.username }}</span>
                                        </div>
                                    </div>
                                </li>

                            {% endfor %}


                        </ul>
                    </div>
                </div>

            {% endif %}

            <!-- search-list end -->
            <!-- news-contain start -->

            {# 分页导航 #}
            <div class="page-box" id="pages">
                <div class="pagebar" id="pageBar">
                    <a class="a1">{{ page.paginator.count }}条</a>
                    {# 上一页的URL地址 #}
                    {% if page.has_previous %}
                        {% if query %}
                            <a href="{% url 'news:search' %}?q={{ query }}&amp;page={{ page.previous_page_number }}"
                               class="prev">上一页</a>
                        {% else %}
                            <a href="{% url 'news:search' %}?page={{ page.previous_page_number }}" class="prev">上一页</a>
                        {% endif %}
                    {% endif %}
                    {# 列出所有的URL地址 #}
                    {% for num in page.paginator.page_range|slice:":10" %}
                        {% if num == page.number %}
                            <span class="sel">{{ page.number }}</span>
                        {% else %}
                            {% if query %}
                                <a href="{% url 'news:search' %}?q={{ query }}&amp;page={{ num }}"
                                   target="_self">{{ num }}</a>
                            {% else %}
                                <a href="{% url 'news:search' %}?page={{ num }}" target="_self">{{ num }}</a>
                            {% endif %}
                        {% endif %}
                    {% endfor %}

                    {# 如果页数大于10，则打两点 #}
                    {% if page.paginator.num_pages > 10 %}
                        ..

                        {% if query %}
                            <a href="{% url 'news:search' %}?q={{ query }}&amp;page={{ page.paginator.num_pages }}"
                               target="_self">{{ page.paginator.num_pages }}</a>
                        {% else %}
                            <a href="{% url 'news:search' %}?page={{ page.paginator.num_pages }}"
                               target="_self">{{ page.paginator.num_pages }}</a>
                        {% endif %}

                    {% endif %}

                    {# 下一页的URL地址 #}
                    {% if page.has_next %}
                        {% if query %}
                            <a href="{% url 'news:search' %}?q={{ query }}&amp;page={{ page.next_page_number }}"
                               class="next">下一页</a>
                        {% else %}
                            <a href="{% url 'news:search' %}?page={{ page.next_page_number }}" class="next">下一页</a>
                        {% endif %}
                    {% endif %}
                </div>
            </div>

            <!-- news-contain end -->
        </div>
        <!-- content end -->
    </div>
{% endblock %}


{% block script %}
    <script src="../../static/js/index.js"></script>
{% endblock %}