D_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('', include('news.urls')),
    path('users/', include('user.urls')),
    path('', include('verifications.urls')),
    path('doc', include('doc.urls')),
    path('course', include('course.urls')),
    path('admin/', include('admin.urls')),

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/doc/urls.py
# -*- coding:utf-8 -*
from django.urls import path
from doc import views


app_name = 'doc'

urlpatterns = [
    path('', views.doc_index, name='index'),
    path('<int:doc_id>/', views.DocDownload.as_view(), name='download'),
]

apps/doc/models.py
from django.db import models

from utils.models import ModelBase
from django.core.validators import MinLengthValidator

class Doc(ModelBase):
    """
    create doc view
    """
    file_url = models.URLField(verbose_name="文件url", help_text="文件url")
    title = models.CharField(max_length=150,validators=[MinLengthValidator(1)], verbose_name="文档标题", help_text="文档标题")
    desc = models.TextField(verbose_name="文档描述", help_text="文档描述")
    image_url = models.URLField(default="", verbose_name="图片url", help_text="图片url")
    author = models.ForeignKey('user.Users', on_delete=models.SET_NULL, null=True)

    class Meta:
        db_table = "tb_docs"   # 指明数据库表名
        verbose_name = "文档"    # 在admin站点中显示的名称
        verbose_name_plural = verbose_name  # 显示的复数名称

    def __str__(self):
        return self.title

apps/doc/views.py
import requests
import logging
from django.shortcuts import render
from django.utils.encoding import escape_uri_path
from django.views import View
from django.conf import settings
from .models import Doc
from django.http import FileResponse,Http404

# 日志器
logger = logging.getLogger('django')



def doc_index(request):
    """渲染文档下载页面"""
    docs = Doc.objects.defer('author','create_time', 'update_time','is_delete').filter(is_delete=False)
    return render(request, 'doc/docDownload.html', locals())


# 文档下载
class DocDownload(View):
    """
    传参：id
    请求方式：GET
    URL:/doc/<int:doc_id>
    流程：id > 从数据库拿到文件地址 > 文件对象 > FileResponse方法返回给用户
    """
    def get(self,request,doc_id):
        # 在数据库中查file_url，获取第一条
        doc = Doc.objects.only('file_url').filter(is_delete=False,id=doc_id).first()
        if doc:
            # 获取文件url并进行路径拼接
            file_url = doc.file_url
            doc_url = settings.SITE_DOMAIN_PORT + file_url
            try:
                # 使用爬虫(requests方法)下载文件对象
                # stream作用：下载大型文件时可以看到下载进度，优化加速
                file = requests.get(doc_url, stream=True)
                # 返回给用户
                res = FileResponse(file)
            except Exception as e:
                logger.info('获取文档内容出现异常:{}'.format(e))
                raise Http404('文件下载异常！')
            # 获取文件类型
            file_type = doc_url.split('.')[-1]
            if not file_type:
                raise Http404('文档url异常！')
            else:
                file_type = file_type.lower()
            # 构造请求头
            if file_type== "pdf":
                res["Content-type"] = "application/pdf"
            elif file_type == "zip":
                res["Content-type"] = "application/zip"
            elif file_type == "doc":
                res["Content-type"] = "application/msword"
            elif file_type == "xls":
                res["Content-type"] = "application/vnd.ms-excel"
            elif file_type == "docx":
                res["Content-type"] = "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
            elif file_type == "ppt":
                res["Content-type"] = "application/vnd.ms-powerpoint"
            elif file_type == "pptx":
                res["Content-type"] = "application/vnd.openxmlformats-officedocument.presentationml.presentation"
            else:
                raise Http404("文档格式不正确！")
            # 对文件名进行转码，用于下载时的显示
            doc_filename = escape_uri_path(doc_url.split('/')[-1])
            # 设置为inline，会直接打开
            # 设置attachment 浏览器才会开始下载
            res["Content-Disposition"] = "attachment; filename*=UTF-8''{}".format(doc_filename)
            return res
        else:
            raise Http404("文档不存在！")

templates/doc/docDownload.html
{% extends 'base/news_index_base.html' %}


{% block title %}
    下载文档
{% endblock %}


{% block link %}
      <link rel="stylesheet" href="../../static/css/doc/docDownload.css">
      <link rel="stylesheet" href="../../static/css/base/side.css">
{% endblock %}


{% block main-contain %}
    <div class="main-contain ">
        <div class="banner">
            <img src="/media/doc_banner_1.jpg" alt="">
        </div>
        <div class="pay-doc-contain">
            <ul class="pay-list">

                {% for doc in docs %}

                    <li class="pay-item">
                        <img src="{{ doc.image_url }}" class="pay-img doc"/>
                        <div class="d-contain">
                            <p class="doc-title">{{ doc.title }}</p>
                            <p class="doc-desc">{{ doc.desc }}</p>

                            <a href="{% url 'doc:download' doc.id %}" class="pay-price">下载</a>
                        </div>
                    </li>

                {% endfor %}

            </ul>
        </div>
    </div>
{% endblock %}


{% block script %}
    <script src="../../static/js/index.js"></script>
{% endblock %}